# Generated by Django 5.2.8 on 2025-11-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='religious_preference',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Other', 'Other'), ('Any', 'Any')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='religious_preference',
            field=models.CharField(blank=True, choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Other', 'Other'), ('Any', 'Any')], max_length=20, null=True),
        ),
    ]
